#!/bin/sh
ssh ubuntu@10.118.10.25 <<EOF
    cd ~/express-long-polling
    git pull origin main
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install v12.19.0
    npm install
    npm install -g forever

    if [ ! -d "/home/ubuntu/forever/express-long-polling/" ]; then
      mkdir -p "/home/ubuntu/forever/express-long-polling/"
    fi;

    # echo "stop all application"
    forever stopall

    # echo "simulate a 20s downtime"
    # sleep 20s

    echo "serve the application"

    forever start -p "/home/ubuntu/forever/express-long-polling" -l "forever.log" -o "/home/ubuntu/forever/express-long-polling/stdout.log" -e "/home/ubuntu/forever/express-long-polling/stderr.log" --append --pidFile "/home/ubuntu/forever/express-long-polling/pidfile" --sourceDir "/home/ubuntu/express-long-polling" --workingDir "/home/ubuntu/express-long-polling" "src/monitor.js"

    exit
EOF
