#!/bin/sh
ssh ubuntu@10.118.10.25 <<EOF
    cd ~/express-long-polling
    git pull origin main
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
    . ~/.nvm/nvm.sh
    nvm install v12.22.6
    npm install
    npm install -g forever pm2

    if [ ! -d "/home/ubuntu/forever/express-long-polling/" ]; then
      mkdir -p "/home/ubuntu/forever/express-long-polling/"
    fi;

    # echo "stop application using pid"
    cat /home/ubuntu/forever/express-long-polling/pidfile | xargs -n1 forever stop

    # stop all the previous child process gracefully
    # npm run kill

    echo "serve the application"
    # nohup node index.js >> app.log 2>&1 &
    nohup npm run start

    exit
EOF
